# Generated by Django 5.0.1 on 2024-02-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_orders_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='name',
            new_name='shipfrom',
        ),
        migrations.AddField(
            model_name='orders',
            name='shipto',
            field=models.CharField(default='blank', max_length=90),
            preserve_default=False,
        ),
    ]
