# Generated by Django 5.0.1 on 2024-02-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_name_orders_shipfrom_orders_shipto'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.CharField(default=1000, max_length=90),
            preserve_default=False,
        ),
    ]
