# Generated by Django 5.0.2 on 2024-03-01 13:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_productreview_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
