# Generated by Django 4.1.2 on 2024-04-24 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_session_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='name',
            new_name='session',
        ),
    ]
