# Generated by Django 4.1.2 on 2024-04-24 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_rename_name_session_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='session',
            new_name='sessionId',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session',
            new_name='sessionName',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='session',
            new_name='sessionName',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='name',
            new_name='urlName',
        ),
    ]
