# Generated by Django 4.1.2 on 2024-04-24 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_rename_session_question_sessionid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='sessionName',
            new_name='sessionId',
        ),
    ]
