# Generated by Django 4.1.2 on 2024-04-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_rename_sessionname_url_sessionid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='user',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='user',
            new_name='userId',
        ),
    ]
