# Generated by Django 4.1.2 on 2024-04-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_rename_user_session_userid_rename_user_url_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='url',
            name='userId',
        ),
        migrations.AddField(
            model_name='session',
            name='userName',
            field=models.CharField(default='sma', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='userName',
            field=models.CharField(default='sma', max_length=100),
            preserve_default=False,
        ),
    ]
