# Generated by Django 4.1.2 on 2024-04-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_remove_session_userid_remove_url_userid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='sessionId',
        ),
        migrations.AddField(
            model_name='question',
            name='ssessionId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
