# Generated by Django 4.1.2 on 2024-04-24 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_remove_question_sessionid_question_ssessionid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='ssessionId',
            new_name='sessionId',
        ),
    ]
