# Generated by Django 4.1.2 on 2024-04-24 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_rename_ssessionid_question_sessionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
